version: "3.9"
services:
  rain:
    container_name: rain
    build:
      context: ./cmd/rain
      dockerfile: Dockerfile
    ports:
      - "6969:6969"
    environment:
      - "MONGO_HOSTNAME=mongo"

  door:
    container_name: door
    build:
      context: ./cmd/door
      dockerfile: Dockerfile
    ports:
      - "6970:6970"
    environment:
      - "MONGO_HOSTNAME=mongo"

  mongo:
    container_name: mongo
    image: mongo:4.4.4
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:2.0.12
    ports:
      - "1883:1883"
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    
volumes:
  mongo:
    driver: local
  mosquitto:
    driver: local
